name = "hui-booking"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "hui-booking-db"
database_id = "279985c5-1201-45b2-8b56-9dc97c2c7a61"
